# -*- coding: utf-8 -*-
"""P1_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yj2r9xEXWFji_kHoGk7AB5Po3jJbo6UV
"""

#皇后
position1 = input().split()
position2 = input().split()
x1,y1 = int(position1[0]),int(position1[1])
x2,y2 = int(position2[0]),int(position2[1])
if checkerboard[x2][y2]==1:
  print("No")
elif x1==x2 and y1==y2 or (abs(x2-x1)!=abs(y2-y1)) and x2!=x1 and y2!=y1:
  print("No")
else:
  dx=(x2-x1) // max(1,abs(x2-x1))
  dy=(y2-y1) // max(1,abs(y2-y1))
  cx,cy=x1+dx,y1+dy
  reachable = True
  while cx!=x2 or cy!=y2:
    if checkerboard[cx][cy]==1:
      reachable = False
      break
    cx,cy=cx+dx,cy+dy
  if reachable:
    print("Yes")
  else:
    print("No")

#皇后
position1 = input().split()
position2 = input().split()
x1,y1 = int(position1[0]),int(position1[1])
x2,y2 = int(position2[0]),int(position2[1])
if (x1==x2 and y1==y2) or (checkerboard[x2][y2]==1):
  print("No")
elif (abs(x2-x1)==2 and abs(y2-y1)==1) or (abs(x2-x1)==1 and abs(y2-y1)==2):
  print("Yes")
else:
  print("No")

#对边：abs(x2-x1)==abs(y2-y1)
#沿y轴走：x2==x1
#沿X轴走：y2==y1
#还需要判断线路上无障碍物
#if 目标有人 则no
#elif 原地不动 or 在非法位置 则 no
#else 在合法位置方向
    #if 起点走到终点，是不是没障碍 无障碍则yes 有障碍则no（计算每次移动方向，recheable